name: Incident Report
description: File an incident report
title: "[Incident]: "
labels: ["incident", "triage"]
assignees:
  - dcmcshan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "An incident happened!"
    validations:
      required: true
  - type: textarea
    id: when
    attributes:
      label: When did this incident happen?
    validations:
      required: true
  - type: dropdown
    id: where
    attributes:
      label: Where did this incident happen?
      multiple: true
      options:
        - Black Rock City
        - Denver Decomp
        - Apogaea
        - Other 10 Principle Event
        - Outside Brulee 
  - type: textarea
    id: resolution
    attributes:
      label: What resolution do you think is appropriate?
    validations:
      required: true 
  - type: checkboxes
    id: terms
    attributes:
      label: Etiquette and Protocol
      description: By submitting this issue, you agree to follow our [Etiquette and Protocol](https://example.com)
      options:
        - label: I agree to follow this organization's Etiquette and Protocol
          required: true
